name: Habit Tracker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.12"

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Django Check
        run: |
          cd backend
          python manage.py check

      - name: Setup Node
        uses: actions/setup-node@v4

        with:
          node-version: 22

      - name: Install Frontend Dependencies
        run: |
          cd HabitTrackerWithRedux
          npm install

      - name: Build React
        run: |
          cd HabitTrackerWithRedux
          npm run build
          